# Operaciones lógicas con perceptrones

Universidad Galileo

Rodrigo Rafael Chang Papa

Carné: 19000625

In [1]:
import numpy as np

***
## Función de activación
Se utiliza una función de activación de escalón.

In [4]:
def activation(z):
    return (z >= 0).astype(np.float)

In [5]:
activation(np.array([1]))

array([1.])

## Transformación afin y definición del perceptrón básico

In [6]:
# Se realiza el producto punto, en forma matricial, entre la entrada y las ponderaciones
def affine_transf(x, weights):
    return np.matmul(x, weights)

In [7]:
affine_transf(np.array([1, 1, 1.]), np.array([1.,1.,-2.]))

0.0

In [19]:
# Definición del perceptrón básico con pesos 'weights'
# Esta función recibe estrictamente entradas X con shape (n, 2) y
# devuelve vectores (n, 1)
def perceptron(x, weights):
    x = np.column_stack((x, np.ones(x.shape[0])))
    return activation(affine_transf(x, weights)).reshape(-1, 1)

In [20]:
X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [21]:
perceptron(X, np.array([1., 1., 0]))

array([[1.],
       [1.],
       [1.],
       [1.]])

## Función AND

In [25]:
weights = np.array([10., 10., -15.])
and_ = perceptron(X, weights)
print("Entradas:")
print(X)
print("Función lógica AND: ")
print(and_)

Entradas:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Función lógica AND: 
[[0.]
 [0.]
 [0.]
 [1.]]


## Función OR

In [66]:
weights = np.array([20., 20., -10.])
or_ = perceptron(np.array(X), weights)
print("Entradas:")
print(X)
print("Función lógica OR: ")
print(or_)

Entradas:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Función lógica OR: 
[[0.]
 [1.]
 [1.]
 [1.]]


## Función NOT

In [29]:
Y = np.array([0, 1]).reshape(-1, 1)

In [33]:
weights = np.array([-1., 0.5])
not_ = perceptron(np.array(Y), weights)

print("Entradas:")
print(Y)
print("Función lógica NOT: ")
print(not_)

Entradas:
[[0]
 [1]]
Función lógica NOT: 
[[1.]
 [0.]]


##  Definición de función XOR

Esta función se puede expresar de forma algebraica como: $$A \oplus B = A\cdot\bar{B} + \bar{A}\cdot B$$

Para su implementación, se utilizarán funciones anónimas compuestas de la función de `perceptron` (que recibe como argumentos de entrada arreglos de numpy con shape n, 2):

In [80]:
and_fn = lambda a, b : perceptron(np.column_stack((a, b)), np.array([10., 10., -15.]))
or_fn = lambda a, b : perceptron(np.column_stack((a, b)), np.array([20., 20., -10.]))
not_fn = lambda x : perceptron(x, np.array([-1., 0.5]))

De esta forma, la función XOR estaría dada por:

In [81]:
xor_fn = lambda a, b : or_fn( and_fn(a, not_fn(b)), and_fn(not_fn(a), b) )

In [82]:
# Obtenemos los valores de XOR
print("Entradas:")
print(X)
print("Función lógica XOR: ")
print(xor_fn(X[:, 0], X[:, 1]))

Entradas:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Función lógica XOR: 
[[0.]
 [1.]
 [1.]
 [0.]]
