In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [23]:
Xtrain = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
Xtrain

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [24]:
Ytrain = np.array([0., 1., 1., 0.]).reshape(-1, 1)
Ytrain

array([[0.],
       [1.],
       [1.],
       [0.]])

## Modelo en keras

In [67]:
# Definición del modelo
model = Sequential()
model.add(Dense(3, input_dim=2, activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='linear'))

# Compilar el modelo 
# mean_squared_error
# binary_crossentropy
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_64 (Dense)             (None, 3)                 9         
_________________________________________________________________
dense_65 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_66 (Dense)             (None, 1)                 3         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [68]:
# Entrenar el modelo
model.fit(Xtrain, Ytrain, epochs=500, batch_size=10, verbose=1)

Epoch 1/500
4/4 [==============================] - 1s 175ms/step - loss: 0.5000 - acc: 0.5000
Epoch 2/500
4/4 [==============================] - 0s 534us/step - loss: 0.4990 - acc: 0.5000
Epoch 3/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4981 - acc: 0.5000
Epoch 4/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4972 - acc: 0.5000
Epoch 5/500
4/4 [==============================] - 0s 976us/step - loss: 0.4963 - acc: 0.5000
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4954 - acc: 0.5000
Epoch 7/500
4/4 [==============================] - 0s 545us/step - loss: 0.4944 - acc: 0.5000
Epoch 8/500
4/4 [==============================] - 0s 3ms/step - loss: 0.4934 - acc: 0.5000
Epoch 9/500
4/4 [==============================] - 0s 654us/step - loss: 0.4925 - acc: 0.5000
Epoch 10/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4915 - acc: 0.5000
Epoch 11/500
4/4 [==============================] - 0s 814us/step - l

Epoch 88/500
4/4 [==============================] - 0s 967us/step - loss: 0.4226 - acc: 0.5000
Epoch 89/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4218 - acc: 0.5000
Epoch 90/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4210 - acc: 0.5000
Epoch 91/500
4/4 [==============================] - 0s 756us/step - loss: 0.4203 - acc: 0.5000
Epoch 92/500
4/4 [==============================] - 0s 824us/step - loss: 0.4195 - acc: 0.5000
Epoch 93/500
4/4 [==============================] - 0s 656us/step - loss: 0.4188 - acc: 0.5000
Epoch 94/500
4/4 [==============================] - 0s 807us/step - loss: 0.4180 - acc: 0.5000
Epoch 95/500
4/4 [==============================] - 0s 810us/step - loss: 0.4172 - acc: 0.5000
Epoch 96/500
4/4 [==============================] - 0s 670us/step - loss: 0.4165 - acc: 0.5000
Epoch 97/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4157 - acc: 0.5000
Epoch 98/500
4/4 [==============================] - 0s 9

Epoch 174/500
4/4 [==============================] - 0s 714us/step - loss: 0.3653 - acc: 0.5000
Epoch 175/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3647 - acc: 0.5000
Epoch 176/500
4/4 [==============================] - 0s 816us/step - loss: 0.3641 - acc: 0.5000
Epoch 177/500
4/4 [==============================] - 0s 688us/step - loss: 0.3636 - acc: 0.5000
Epoch 178/500
4/4 [==============================] - 0s 965us/step - loss: 0.3630 - acc: 0.5000
Epoch 179/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3625 - acc: 0.5000
Epoch 180/500
4/4 [==============================] - 0s 827us/step - loss: 0.3619 - acc: 0.5000
Epoch 181/500
4/4 [==============================] - 0s 663us/step - loss: 0.3614 - acc: 0.5000
Epoch 182/500
4/4 [==============================] - 0s 886us/step - loss: 0.3608 - acc: 0.5000
Epoch 183/500
4/4 [==============================] - 0s 818us/step - loss: 0.3603 - acc: 0.5000
Epoch 184/500
4/4 [=========================

Epoch 260/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3240 - acc: 0.5000
Epoch 261/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3236 - acc: 0.5000
Epoch 262/500
4/4 [==============================] - 0s 858us/step - loss: 0.3232 - acc: 0.5000
Epoch 263/500
4/4 [==============================] - 0s 654us/step - loss: 0.3229 - acc: 0.5000
Epoch 264/500
4/4 [==============================] - 0s 600us/step - loss: 0.3225 - acc: 0.5000
Epoch 265/500
4/4 [==============================] - 0s 504us/step - loss: 0.3221 - acc: 0.5000
Epoch 266/500
4/4 [==============================] - 0s 1ms/step - loss: 0.3217 - acc: 0.5000
Epoch 267/500
4/4 [==============================] - 0s 786us/step - loss: 0.3213 - acc: 0.5000
Epoch 268/500
4/4 [==============================] - 0s 534us/step - loss: 0.3209 - acc: 0.5000
Epoch 269/500
4/4 [==============================] - 0s 694us/step - loss: 0.3205 - acc: 0.5000
Epoch 270/500
4/4 [===========================

Epoch 346/500
4/4 [==============================] - 0s 538us/step - loss: 0.2955 - acc: 0.5000
Epoch 347/500
4/4 [==============================] - 0s 503us/step - loss: 0.2953 - acc: 0.5000
Epoch 348/500
4/4 [==============================] - 0s 969us/step - loss: 0.2950 - acc: 0.5000
Epoch 349/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2947 - acc: 0.5000
Epoch 350/500
4/4 [==============================] - 0s 851us/step - loss: 0.2945 - acc: 0.5000
Epoch 351/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2942 - acc: 0.5000
Epoch 352/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2939 - acc: 0.5000
Epoch 353/500
4/4 [==============================] - 0s 495us/step - loss: 0.2937 - acc: 0.5000
Epoch 354/500
4/4 [==============================] - 0s 922us/step - loss: 0.2934 - acc: 0.5000
Epoch 355/500
4/4 [==============================] - 0s 583us/step - loss: 0.2932 - acc: 0.5000
Epoch 356/500
4/4 [===========================

Epoch 432/500
4/4 [==============================] - 0s 964us/step - loss: 0.2767 - acc: 0.5000
Epoch 433/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2765 - acc: 0.5000
Epoch 434/500
4/4 [==============================] - 0s 1ms/step - loss: 0.2763 - acc: 0.5000
Epoch 435/500
4/4 [==============================] - 0s 960us/step - loss: 0.2762 - acc: 0.5000
Epoch 436/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2760 - acc: 0.5000
Epoch 437/500
4/4 [==============================] - 0s 882us/step - loss: 0.2758 - acc: 0.5000
Epoch 438/500
4/4 [==============================] - 0s 790us/step - loss: 0.2757 - acc: 0.5000
Epoch 439/500
4/4 [==============================] - 0s 991us/step - loss: 0.2755 - acc: 0.5000
Epoch 440/500
4/4 [==============================] - 0s 854us/step - loss: 0.2753 - acc: 0.5000
Epoch 441/500
4/4 [==============================] - 0s 712us/step - loss: 0.2752 - acc: 0.5000
Epoch 442/500
4/4 [===========================

In [69]:
model.predict(Xtrain)

array([[0.37060377],
       [0.37060377],
       [0.37060377],
       [0.37060377]], dtype=float32)